
export const selectPhoneNumber = (state) => state.phoneNumber;
export const selectPatientDetails = (state) => state.patientDetails;
export const selectPFirstName = (state) => state.pFirstName;
export const selectPLastName = (state) => state.pLastName;
//export const selectPMobileNumber = (state) => state.pMobileNumber ;
export const selectPOrCaregiver = (state) => state.pOrCaregiver;
export const selectPDob = (state) => state.pDob;
export const selectPAge = (state) => state.pAge;
export const selectPGender = (state) => state.pGender;
export const selectPMaritialStatus = (state) => state.spMaritialStatus;
export const selectPAlternateNo = (state) => state.pAlternateNo ;
export const selectPHouse = (state) => state.pHouse ;
export const selectPLocality = (state) => state.pLocality ;
export const selectPCity = (state) => state.pCity ;
export const selectPDistrict = (state) => state.pDistrict ;
export const selectPState = (state) => state.pState ;
export const selectPPincode = (state) => state.pPincode ;
export const selectCFirstName = (state) => state.cFirstName ;
export const selectCLastName = (state) => state.cLastName ;
export const selectCMobNo = (state) => state.cMobNo ;
export const selectCRelation = (state) => state.cRelation ;
export const selectCareGiverOrOther = (state) => state.careGiverOrOther;
export const selectOtherFirstName = (state) => state.oFirstName;
export const selectOLastName = (state) => state.oLastName;
export const selectOMobileNumber = (state) => state.oMobileNumber;
export const selectORelation = (state) => state.otherRelation;
export const selectKinHouse = (state) => state.kinHouse;
export const selectkinLocality = (state) => state.kinLocality;
export const selectkinCity = (state) => state.kinCity;
export const selectkinDistrict = (state) => state.kinDistrict;
export const selectkinState = (state) => state.kinState;
export const selectkinPincode = (state) => state.kinPincode;
export const selectTestName = (state) => state.testName;
export const selectTestDate = (state) => state.testDate;
export const selectUserName = (state) => state.userName;
export const selectUserReport = (state) => state.userReport;